name: MoroBounty
version: 2.0.0
main: net.morosmp.bounty.MoroBounty
api-version: '1.21'
description: Physical item bounty system for Hardcore Lifesteal servers.

commands:
  bounty:
    description: Open the bounty system
    usage: /bounty create <player>
