# MoroStats Cloud Configuration
# Paste your MongoDB Atlas URI here (Connect -> Connect your application)
# Example: mongodb+srv://username:password@cluster0.xxxxx.mongodb.net/?retryWrites=true&w=majority
mongodb-uri: ""
database-name: "morosmp"
