# MoroKillSound Configuration

# Kill-sound settings when a player gets a kill
sound:
  # Bukkit API sound key (example: ENTITY_WITHER_SPAWN, ENTITY_EXPERIENCE_ORB_PICKUP)
  name: "ENTITY_WITHER_SPAWN"
  
  # Volume (from 0.0 to 1.0+)
  volume: 1.0
  
  # Pitch/Speed (from 0.5 to 2.0). 1.0 = default, 2.0 = high/fast.
  pitch: 1.0
  
  # Should the sound play for nearby players or only the killer?
  play-to-all: false
  
  # If play-to-all is true, what radius can hear this sound?
  radius: 20.0
